name: Update Readme

on:
  schedule:
    - cron: "0 */12 * * *"  # Cada 12 horas
  workflow_dispatch:        # Permite ejecuci√≥n manual

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    steps:
      - uses: actions/checkout@v4
      - name: Update recent activity in README
        uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
